### ISSUE TITLE
Unable to install the plugin

### ISSUE THREAD

**Issue by formigadiablo** [onozaty/redmine-view-customize#102]
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /opt/redmine/redmine-5.0.3)
Rails Error: Unable to access log file. Please ensure that /opt/redmine/redmine-5.0.3/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/redmine/redmine-5.0.3/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
rake aborted!
Could not create directory /opt/redmine/redmine-5.0.3/public/plugin_assets/view_customize/stylesheets: Permission denied @ dir_s_mkdir - /opt/redmine/redmine-5.0.3/public/plugin_assets/view_customize
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:51:in `rescue in mirror_assets'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:48:in `mirror_assets'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:143:in `each'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:143:in `mirror_assets'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:99:in `block in create_assets_reloader'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/file_update_checker.rb:83:in `execute'
/opt/redmine/redmine-5.0.3/config/initializers/30-redmine.rb:25:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:681:in `block in load_config_initializer'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:680:in `load_config_initializer'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:633:in `each'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:633:in `block in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/redmine/redmine-5.0.3/public/plugin_assets/view_customize
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:49:in `mirror_assets'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:143:in `each'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:143:in `mirror_assets'
/opt/redmine/redmine-5.0.3/lib/redmine/plugin_loader.rb:99:in `block in create_assets_reloader'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/file_update_checker.rb:83:in `execute'
/opt/redmine/redmine-5.0.3/config/initializers/30-redmine.rb:25:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:681:in `block in load_config_initializer'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:680:in `load_config_initializer'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:633:in `each'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:633:in `block in <class:Engine>'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:50:in `tsort_each_child'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

What can I do?

**Comment by onozaty** [comment]
It appears that you are being told that you do not have write permissions.
Does the user who ran bundle exec have write permission to `/opt/redmine/redmine-5.0.3/` ?

Thanks.

**Comment by formigadiablo** [comment]
I will try to use sudo maybe then works
Thanks.

**Comment by formigadiablo** [comment]
> It appears that you are being told that you do not have write permissions. Does the user who ran bundle exec have write permission to `/opt/redmine/redmine-5.0.3/` ?
> 
> Thanks.

Solved Thanks!
