### ISSUE TITLE
NoMethodError: undefined method `represent_boolean_as_integer=' for nil:NilClass encountered with Redmine 4.1.0-9

### ISSUE THREAD

**Issue by iamriz** [onozaty/redmine-view-customize#108]
Hello, May I ask help on this? Tried to install the plugin in redmine-4.1.0-9, but an error is found with logs as below.

> C:\Bitnami\redmine-4.1.0-9\apps\redmine\htdocs\plugins\view_customize>C:\Bitnami\redmine-4.1.0-9\ruby\bin\bundle exec C:\Bitnami\redmine-4.1.0-9\ruby\bin\rake redmine:plugins:migrate RAILS_ENV=production --trace
> (in C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs)
> rake aborted!
> NoMethodError: undefined method `represent_boolean_as_integer=' for nil:NilClass
> C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs/config/application.rb:60:in `<class:Application>'
> C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs/config/application.rb:21:in `<module:RedmineApp>'
> C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs/config/application.rb:20:in `<top (required)>'
> C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs/Rakefile:5:in `require'
> C:/Bitnami/redmine-4.1.0-9/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
> C:/Bitnami/redmine-4.1.0-9/ruby/lib/ruby/gems/2.5.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> C:/Bitnami/redmine-4.1.0-9/ruby/bin/rake:23:in `load'
> C:/Bitnami/redmine-4.1.0-9/ruby/bin/rake:23:in `<main>'

The bundle install command seems to be successful with the log as follows.

> C:\Bitnami\redmine-4.1.0-9\apps\redmine\htdocs\plugins\view_customize>C:\Bitnami\redmine-4.1.0-9\ruby\bin\bundle install --without development test
> Fetching gem metadata from https://rubygems.org/...........
> Fetching gem metadata from https://rubygems.org/.
> Resolving dependencies......
> Using rake 13.0.6
> Using concurrent-ruby 1.2.2
> Using i18n 1.13.0
> Using minitest 5.15.0
> Using tzinfo 2.0.6
> Using zeitwerk 2.6.8
> Using activesupport 6.1.7.3
> Using builder 3.2.4
> Using erubi 1.12.0
> Using racc 1.6.2
> Using nokogiri 1.12.5 (x64-mingw32)
> Using rails-dom-testing 2.0.3
> Using crass 1.0.6
> Using loofah 2.21.3
> Using rails-html-sanitizer 1.5.0
> Using actionview 6.1.7.3
> Using rack 2.2.7
> Using rack-test 2.1.0
> Using actionpack 6.1.7.3
> Using nio4r 2.5.9
> Using websocket-extensions 0.1.5
> Using websocket-driver 0.7.5
> Using actioncable 6.1.7.3
> Using globalid 1.1.0
> Using activejob 6.1.7.3
> Using activemodel 6.1.7.3
> Using activerecord 6.1.7.3
> Using marcel 1.0.2
> Using mini_mime 1.1.2
> Using activestorage 6.1.7.3
> Using digest 3.1.1
> Using io-wait 0.3.0
> Using timeout 0.3.2
> Using net-protocol 0.1.2
> Using strscan 3.0.6
> Using net-imap 0.2.2
> Using net-pop 0.1.2
> Using net-smtp 0.3.0
> Using mail 2.8.1
> Using actionmailbox 6.1.7.3
> Using actionmailer 6.1.7.3
> Using actiontext 6.1.7.3
> Using activerecord-compatible_legacy_migration 0.1.2
> Using bundler 1.16.6
> Using method_source 1.0.0
> Using thor 1.2.2
> Using railties 6.1.7.3
> Using sprockets 4.2.0
> Using sprockets-rails 3.4.2
> Using rails 6.1.7.3
> Bundle complete! 3 Gemfile dependencies, 50 gems now installed.
> Gems in the groups development and test were not installed.
> Use `bundle info [gemname]` to see where a bundled gem is installed.

Any feedback would be much appreciated. Thank you.

**Comment by onozaty** [comment]
I did not know if the following command is correct.

```
C:\Bitnami\redmine-4.1.0-9\ruby\bin\bundle exec C:\Bitnami\redmine-4.1.0-9\ruby\bin\rake redmine:plugins:migrate RAILS_ENV=production --trace
```

Could you also try the following designation?

```
C:\Bitnami\redmine-4.1.0-9\ruby\bin\bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
```

Also, go to C:\Bitnami\redmine-4.1.0-9\apps\redmine\htdocs and run it.

Thanks.

**Comment by iamriz** [comment]
Hi @onozaty ,
-----
C:\Bitnami\redmine-4.1.0-9\ruby\bin\bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace
Also, go to C:\Bitnami\redmine-4.1.0-9\apps\redmine\htdocs and run it.
-----
The above worked.
Thank you very much.
