### ISSUE TITLE
Add user mails to ViewCustomize context

### ISSUE THREAD

**Issue by JGallot** [onozaty/redmine-view-customize#110]
Hello,

Will it be possible in the next version of this plugin to access user's mails through ViewCustomize.context.user ?

Thanks by advance.

PS : working on redmine 5.0.5

**Comment by onozaty** [comment]
Hi @JGallot 

I will consider adding it.
For reference, could you please tell us how you would use user's mails?

Thanks

**Comment by JGallot** [comment]
HI,

With this enhancement we could show the default phone number of the current user and he can modify it if needed.

Thanks

**Comment by onozaty** [comment]
Release at v3.4.0.
