### ISSUE TITLE
unable install the plugins for view customize in ubuntu 

### ISSUE THREAD

**Issue by mohamedabdulkadar** [onozaty/redmine-view-customize#115]
unable install the plugins for view customize in ubuntu ,

can anyone elaborate the same

**Comment by onozaty** [comment]
What steps did you take to install it?
If you can tell us the procedure, error logs, etc., I may be able to help.

Thanks.

**Comment by mohamedabdulkadar** [comment]
cd {RAILS_ROOT}/plugins 
git clone https://github.com/onozaty/redmine-view-customize.git view_customize
"after the clone"
cd ../
"getting gem not located issue "
bundle install --without development test
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
we need to configure this in dev environment

**Comment by onozaty** [comment]
Do you mean you want to install in RAILS_ENV=development?

If you do so, first delete the following description in `.bundle/config`.

```
BUNDLE_WITHOUT: "development:test"
```

Then install for development.

```
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV=development
```

Thanks.

**Comment by mohamedabdulkadar** [comment]
after delete bundle/config
run the command 
getting error be like
BUNDLE_WITHOUT: "development:test"
error : BUNDLE_WITHOUT:: command not found
bundle install
error: could not locate gemfile
bundle exec rake redmine:plugins:migrate RAILS_ENV=development
error : Could not locate Gemfile or .bundle/ directory

Kindly give the resolution for this, 

Note : i'm using ubuntu OS

**Comment by onozaty** [comment]
In which directory are you running `bundle install`?
If you are not running it in the Redmine installation folder, then run it in the Redmine installation folder.

Note: I'm also checking on Ubuntu.
