### ISSUE TITLE
Trouble in installation

### ISSUE THREAD

**Issue by pachiras** [onozaty/redmine-view-customize#123]
Hello, thank you for sharing the great plugin!
But I am having a trouble in the installation.

I'm using a bitnami/redmine container from: https://artifacthub.io/packages/helm/bitnami/redmine/25.0.0.
The application version is 5.0.6.

Here is what I did:
``` bash
# pwd
/bitnami/redmine
# ls
config  files  plugins  public
# ls plugins
redmine_absolute_dates  redmine_hide_sidebar  view_customize
# bundle config set --local without 'development test'
You are replacing the current local value of without, which is currently "development:test"
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/opt/bitnami/ruby/bin/bundle:25:in `load'
/opt/bitnami/ruby/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
# find . -iname "*rake*"
# 
```

Since I am not familiar with RoR, I have no clue about how to fix this.
I would appreciate if you could give me a hint.
Thank you.

**Comment by onozaty** [comment]
Looking at the documentation below, it looks like the plugin is located at `/opt/bitnami/redmine/plugins`.

* https://docs.bitnami.com/aws/apps/redmine/configuration/install-plugins/

Can you please try it in a different placement?

Also, it seems that bundle install is missing from the procedure.

Thanks.

**Comment by pachiras** [comment]
I appreciate your quick reply.

You are right. The plugins should be placed in `/opt/bitnami/redmine/plugins`.
But somehow the `plugin` folder is just a symlink to `/bitnami/redmine/plugins` in my container.

So after `cd` to `/opt/bitnami/redmine`, all your installation steps including `bundle install`, which I missed before, were successfully executed!

But sadly, the server restarting process failed at the db migration.
My container is running on a kubernetes cluster.
And I found that the bitnami chart seems to have some issues about plugins:

https://github.com/bitnami/charts/issues/1380
https://github.com/bitnami/charts/issues/15389

I will struggle about it a little bit more.
Anyway thank you for your time. It really helped.
