### ISSUE TITLE
Conditional custom fields with this plugin.

### ISSUE THREAD

**Issue by yingsheng658** [onozaty/redmine-view-customize#14]
Hi onozaty,

Our Redmine System have two custom fields as below,
![image](https://user-images.githubusercontent.com/28344065/34354627-a5a920de-ea6a-11e7-87e8-290f09c1905e.png)
![image](https://user-images.githubusercontent.com/28344065/34354648-bd843fae-ea6a-11e7-92a1-679955a26074.png)
If we would like to make only "#[Image release]" and "#[Travel]" items can be selected in 2nd level when "#[Routine task]" be selected in 1st level,can we apply this plugin or not?
If it does work,could you give me a favor?thanks in advanced.

**Comment by onozaty** [comment]
It closes because it duplicates the following Issues.
* https://github.com/onozaty/redmine-view-customize-scripts/issues/14
