### ISSUE TITLE
Conditional custom fields - max size list field

### ISSUE THREAD

**Issue by EvgeniyKorepov** [onozaty/redmine-view-customize#22]
Is there a limit to the size of the field?
I'm trying to add a field with 1200 lines, but get an error :
```
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
```
Thank you in advance for your response!

P.S. 700 lines are added normally

**Comment by EvgeniyKorepov** [comment]
It looks like this database restriction on the text type field is 64 KB

**Comment by EvgeniyKorepov** [comment]
All the same it was a limitation in the database.
Did
```
ALTER TABLE custom_fields MODIFY possible_values MEDIUMTEXT;
```
And now the possible size of the list has increased from 65,535 characters to 16,777,215.

**And thanks for your plugin - it's amazing!**

**Comment by EvgeniyKorepov** [comment]
I managed to put long lists in the field:
```ALTER TABLE custom_fields MODIFY possible_values MEDIUMTEXT;```

But now I came across a new problem. Apparently now javascript cuts the list - I get a cropped child list when I select the last parent item. Those. instead of 50 lines, I only have 3
I use this javascript:
```
$(function() {

  // Note that you should change these IDs according to your environment.
  var parentFieldId = 'issue_custom_field_values_1';
  var childFieldId = 'issue_custom_field_values_8';

  // define Conditions
  var isTarget = function(child, parent) {
    // This is a left-hand match sample
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
        child.show();
      } else {
        child.hide();
      }
    });
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```
Unfortunately I'm not strong in javascript, could you tell me the solution to the problem? Thank you in advance!

**Comment by onozaty** [comment]
Hi @EvgeniyKorepov 

Please tell me a bit more to understand the problem contents.

* What values are in the parent list and the child list?
* Please tell me which item you selected when a problem occurred.

Thanks

**Comment by EvgeniyKorepov** [comment]
@onozaty Here are two files with lists. Encoding utf8 language Russian.
City - parent, Street - child list.
Problem occurred with select last two City "Юбилейный-93" and "Яблоновский". 

If you delete for example 100 rows from the street list first, then when the last cities are selected, +100 streets appear. As if there is some kind of restriction on the number of characters being processed.

[UTM5RedmineCity.txt](https://github.com/onozaty/redmine-view-customize/files/2280830/UTM5RedmineCity.txt)
[UTM5RedmineStreet.txt](https://github.com/onozaty/redmine-view-customize/files/2280831/UTM5RedmineStreet.txt)

**Comment by onozaty** [comment]
If View customize is disabled, is it all displayed in the Street list?
Redmine may have an upper limit on the number of listings.

**Comment by EvgeniyKorepov** [comment]
@onozaty No, the list is shown completely. The upper limit was in the MySQL database, the TEXT field was 64KB, I changed to the MEDIUMTEXT - now the limit is 16MB

![image](https://user-images.githubusercontent.com/35364901/44002164-43d64c10-9e47-11e8-85aa-77360fe3c669.png)

**Comment by EvgeniyKorepov** [comment]
There was only one reason - javascript

**Comment by EvgeniyKorepov** [comment]
Very strange. The entire list is in the source page of the page. But the drop-down list does not work. 
I'm at a loss.
![image](https://user-images.githubusercontent.com/35364901/44002294-0d702e3c-9e49-11e8-94c5-c50a1bebab5d.png)

**Comment by EvgeniyKorepov** [comment]
I cut out a filtered and filtered drop-down list of a separate html file:
Google Chrome - not worked.
Internet Explorer and Microsoft Edge - all worked.

**What is the glitch of Chrome**

**Comment by onozaty** [comment]
Okay
The following code use remove / add items.

```javascript
$(function() {

  // Note that you should change these IDs according to your environment.
  var parentFieldId = 'issue_custom_field_values_1';
  var childFieldId = 'issue_custom_field_values_8';

  var childField = $('#' + childFieldId);
  var childOptionsClone = childField.find('option').clone();

  // define Conditions
  var isTarget = function(child, parent) {
    // This is a left-hand match sample
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

    childField.empty();
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    childOptionsClone.each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
        childField.append(child);
      }
    });

    childField.val('');
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```

**Comment by EvgeniyKorepov** [comment]
Not worked :-(  The child list is filled with all values at once and does not change when the parent list is changed.
![image](https://user-images.githubusercontent.com/35364901/44003139-da10865a-9e56-11e8-8827-25f4e978274f.png)

**Comment by onozaty** [comment]
Is any error displayed on the console?
I tried it, it looks like it works fine.

![snapcrab_ - redmine - google chrome_2018-8-12_23-44-44_no-00](https://user-images.githubusercontent.com/47337/44003199-dda9acd2-9e89-11e8-8c1f-ca3aa3f1cecd.png)

**Comment by EvgeniyKorepov** [comment]
No errors :-( Maybe I was wrong somewhere. Now I delete all the fields, scripts and create anew.
![image](https://user-images.githubusercontent.com/35364901/44003297-2c220ef8-9e59-11e8-8550-472caa92a43b.png)

**Comment by EvgeniyKorepov** [comment]
The script earned correctly! But it works correctly only with the default tracker :-(
After switching the tracker - it works correctly stops.
![image](https://user-images.githubusercontent.com/35364901/44003444-6a2dc122-9e5b-11e8-8876-c09ec208c993.png)

Here, after switching the tracker, the script no longer works
![image](https://user-images.githubusercontent.com/35364901/44003467-b58c8da6-9e5b-11e8-98b3-69c9d138c148.png)

**Comment by onozaty** [comment]
I made a mistake.
Please try it.

```javascript
$(function() {

  // Note that you should change these IDs according to your environment.
  var parentFieldId = 'issue_custom_field_values_1';
  var childFieldId = 'issue_custom_field_values_8';

  var childOptionsClone = $('#' + childFieldId + ' > option').clone();

  // define Conditions
  var isTarget = function(child, parent) {
    // This is a left-hand match sample
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

    var childField = $('#' + childFieldId);

    childField.empty();
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    childOptionsClone.each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
        childField.append(child);
      }
    });

    childField.val('');
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```

**Comment by EvgeniyKorepov** [comment]
The script starts and fills in the childOptionsClone once, when the page loads. 
Naturally, the field issue_custom_field_values_8 does not exist at this moment. 
Therefore, when changing the tracker and the appearance of the field issue_custom_field_values_8, there is nothing to fill it with.

**Comment by onozaty** [comment]
Fixed. try it.

```javascript
$(function() {

  // Note that you should change these IDs according to your environment.
  var parentFieldId = 'issue_custom_field_values_1';
  var childFieldId = 'issue_custom_field_values_8';

  var childOptionsClone = $('#' + childFieldId + ' > option').clone();

  // define Conditions
  var isTarget = function(child, parent) {
    // This is a left-hand match sample
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

    var childField = $('#' + childFieldId);
    var childFieldVal = childField.val();

    childField.empty();
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    childOptionsClone.each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
        childField.append(child);
      }
    });

    childField.val(childFieldVal);
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    childOptionsClone = $('#' + childFieldId + ' > option').clone();
    narrowChildField();
  };
});
```

**Comment by EvgeniyKorepov** [comment]
It is wonderful! Everything worked perfectly! Thank you very much!

**Comment by onozaty** [comment]
You are welcome :smile:
