### ISSUE TITLE
Redmine Internal Server Error with 1.2.0 

### ISSUE THREAD

**Issue by peney83** [onozaty/redmine-view-customize#29]
hi @onozaty
I install the plugin with the version 1.2.0, it cause the Redmine do not work and show an internal error. The problem is the same as above .

The env
`
Environment:
Redmine version 3.3.0.stable
Ruby version 2.1.9-p490 (2016-03-30) [x86_64-linux]
Rails version 4.2.6
Environment production
Database adapter Mysql2

`

the log is

`
Rendered news/_news.html.erb (12.4ms)
Rendered welcome/index.html.erb within layouts/base (132.2ms)
Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (1.0ms)
Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.3ms)
Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (1.1ms)
Completed 500 Internal Server Error in 569ms (ActiveRecord: 15.5ms)

ActionView::Template::Error (undefined method roles' for #<User:0x0055bdfd8e4868>): 17: <script type="text/javascript" src="/chartkick/Chart.bundle.min.js"></script> 18: <%= javascript_heads %> 19: <%= heads_for_theme %> 20: <%= call_hook :view_layouts_base_html_head %> 21:  22: <%= yield :header_tags -%> 23: </head> plugins/view_customize/lib/view_customize/view_hook.rb:82:increate_view_customize_context'
plugins/view_customize/lib/view_customize/view_hook.rb:10:in view_layouts_base_html_head' lib/redmine/hook.rb:61:inblock (2 levels) in call_hook'
lib/redmine/hook.rb:61:in each' lib/redmine/hook.rb:61:inblock in call_hook'
lib/redmine/hook.rb:58:in tap' lib/redmine/hook.rb:58:incall_hook'
lib/redmine/hook.rb:96:in call_hook' app/views/layouts/base.html.erb:20:in_app_views_layouts_base_html_erb___3024194164021486896_47137250057600'
lib/redmine/sudo_mode.rb:63:in sudo_mode' plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:incall'

**Comment by Dragon8864** [comment]
Hi @onozaty,
I had same problem, but with 1 treatment, this plugin temporary works.

When I comment out view_hook.rb's line 82, this works smoothly.
' just this line
"roles" => user.roles.map {|role| { "id" => role.id, "name" => role.name }},
'

I think "roles" column doesn't exist in DB's user table.
( When I watched my redmine's DB/schema.rb, "user" table, there isn't "roles" column.
  Just there is boolean variable "admin".)

So, Would you check "view_hook.rb" again ?

~~~~~~~~~~~~~~
I always customize my redmine with this plugin.
Thank you for creating this plugin !!

**Comment by onozaty** [comment]
Hi @Dragon8864 @peney83 

I fixed problem by version 1.2.2.
Please try it.

**Comment by peney83** [comment]
@onozaty , Thanks for your quick response and fix problem.

But   I use your [link_custom_field.js](https://github.com/onozaty/redmine-view-customize-scripts/blob/master/link_custom_field.js)  in Redmine ,  and change the "id" 


```
var parentFieldId = '17';
var childFieldId = '16';
```

and view customize configuration:

```
Path pattern:	/issues/
Insertion position:	Head of all pages
Type:	JavaScript
Enabled: true
```


custom_field in mysql ：

```
mysql> select id,name,field_format,possible_values  from custom_fields where name = "test"||name="test1";
+----+-------+--------------+------------------------------------------+
| id | name  | field_format | possible_values                          |
+----+-------+--------------+------------------------------------------+
| 16 | test1 | list         | ---
- A-1
- A-2
- A-3
- B-1
- B-2
- B-3
 |
| 17 | test  | list         | ---
- A
- B
                             |
+----+-------+--------------+------------------------------------------+
2 rows in set (0.00 sec) 

```

It do not work, please help me to check it ,thanks . Do you need any debug information? .
for example in create new issue
![2018-10-03_11-38-45](https://user-images.githubusercontent.com/29172956/46389124-c8f28880-c702-11e8-8072-2e6a23f4b7d2.jpg)

**Comment by onozaty** [comment]
Hi @peney83 

It is necessary to add an id after `issue_custom_field_values_`.

```javascript
  var parentFieldId = 'issue_custom_field_values_17';
  var childFieldId = 'issue_custom_field_values_16';
```

**Comment by onozaty** [comment]
@peney83 

Could you show me the whole code?
Also check that there is no error in the browser console.

**Comment by peney83** [comment]
@onozaty 
this is the whole javascript ：
‘’‘
//
// 
// Path pattern: /issues/
// Type: JavaScript
$(function() {
  var parentFieldId = 'issue_custom_field_values_17';
  var childFieldId = 'issue_custom_field_values_16';
  printf("parentFieldId :"+parentFieldId )


  // 
  var isTarget = function(child, parent) {
    // 
    return child.text().indexOf(parent.text()) == 0;
  }

  // 
  var narrowChildField = function() {

    // 
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      // 
      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
      }
    });
  }

  // 
  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  
  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
’‘’

**Comment by onozaty** [comment]
Hi @peney83 

Sorry, Please also tell me the contents of `Path pattern`, `Insertion position` and `Type`.

**Comment by peney83** [comment]
@onozaty 

Thanks for your quick response .  

'''
Path pattern:	/issues/
Insertion position:	Head of all pages
Type:	JavaScript
Enabled: true
'''

**Comment by Dragon8864** [comment]
@onozaty 
Thanks for  your quick fix. I use this comfortable.

@peney83 
Did you check line 4?
I looked at JS code, maybe forget " ; " at line 4
'
printf("parentFieldId :"+parentFieldId )
'

**Comment by peney83** [comment]
@Dragon8864 

Thanks for your help.  yes ,it is my fault for test code in "printf("parentFieldId :"+parentFieldId )". Now the script is work normally.
@onozaty 
Thanks for your javascript and plug-in. it is work well .
