### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by galaa07** [onozaty/redmine-view-customize#32]
HELP me
How to fix this error

Started GET "/redmine/" for 127.0.0.1 at 2019-01-10 08:37:03 +0800
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
  Rendered welcome/index.html.erb within layouts/base (0.0ms)
Completed 500 Internal Server Error in 359ms (ActiveRecord: 31.2ms)

ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.view_customizes' doesn't exist: SELECT `view_customizes`.* FROM `view_customizes`):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  plugins/view_customize/lib/view_customize/view_hook.rb:47:in `match_customize'
  plugins/view_customize/lib/view_customize/view_hook.rb:38:in `create_view_customize_html'
  plugins/view_customize/lib/view_customize/view_hook.rb:13:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___343716820_33568284'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by isndev** [comment]
Same issue, command was executed

**Comment by Mattani** [comment]
I think  you may clone the repository as 'redmine-view-customize'
It should be 'view_customize'

so, kindly you should do as follows:
```
cd /your-path-to-redmine/plugins
mv redmine-view-customize view_customize
cd ..
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```


then
