### ISSUE TITLE
Could not open view_customizes/2 page : The action '2' could not be found for ViewCustomizesController

### ISSUE THREAD

**Issue by volcom** [onozaty/redmine-view-customize#33]
I recently installed the plugin as advice. I tried some customizations.
But I can't edit them because of this error.
Is there a fix?

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

**Comment by volcom** [comment]
I think the url should be like redmine/view_customizes/show?id=1
I think there is a fix needed

**Comment by volcom** [comment]
the url should be like "redmine.de/view_customizes/edit/3" instead of "redmine.de/view_customizes/3" or "redmine.de/view_customizes/3/edit"

there is fix needed

**Comment by volcom** [comment]
Hi,
I Can view the List of view_customizes.
When i click a number to Access the detail screen the error occurs.
When i enter the url manually as describe above i am able to edit the view_customize item.
When i Click „ok“ to save the edit the error occurs again.

**Comment by onozaty** [comment]
Thank you for the information.

In the my environment , Redmine 3.4.2 is running without problems. I do not know the cause yet.
If you can, try version 1.2.2 of View customize.

https://github.com/onozaty/redmine-view-customize/releases/tag/v1.2.2

**Comment by onozaty** [comment]
The environment I tried is as follows.
In this environment, the problem is not happening.

![image](https://user-images.githubusercontent.com/47337/51429294-9be5c980-1c50-11e9-8591-879b2585af79.png)

**Comment by volcom** [comment]
I als tested another environment and it works perfectly, so it seems to be an environment issue.
I think we can close this thread.
