### ISSUE TITLE
Feature to disable all cutomizes

### ISSUE THREAD

**Issue by vividtone** [onozaty/redmine-view-customize#45]
I think it would be nice if ViewCustomize plugin has a feature to temporarily disable all customizes at once.

Suppose that a Redmine instance which has dozens view customizes and the admin is to troubleshoot unexpected behavior. The admin can quickly determine whether the issue is caused by some customize or not if ViewCustomize plugin has a feature to disable all customize with one-click. Currently, the admin has to disable customizes one by one. That is really time-consuming and boring work.

Thank you for open-sourcing the great plugin.

**Comment by onozaty** [comment]
Thank you for a very good suggestion.
I will implement this feature.

**Comment by onozaty** [comment]
Released in v2.4.0.

![change-enable](https://user-images.githubusercontent.com/47337/64475576-a2b15480-d1bf-11e9-926c-458fd2d5cd00.gif)
