### ISSUE TITLE
not working in redmine 4.0.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize#57]
plugins/view_customi/lib/view_customize/view_hook.rb:15:in `view_layouts_base_html_head'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___2726933900762255495_46985971666360'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Started GET "/" for 172.18.25.65 at 2020-03-11 00:18:00 +0200
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (1.7ms)
Completed 500 Internal Server Error in 53ms (ActiveRecord: 14.8ms)
  
ActionView::Template::Error (uninitialized constant RedmineViewCustomize::ViewHook::ViewCustomize):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>

**Comment by onozaty** [comment]
Hi @ashrafalzyoud 

The directory name seems to be incorrect.

`plugins/view_customi` -> `plugins/view_customize`

Thanks.
