### ISSUE TITLE
javascript give error Network error IN MY FIREWALL

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize#67]
TYPE ONLY JAVA SCRIPT GIVE THIS ERROR ONLY
-------------------------------
Network Error (tcp_error)
--
A communication error occurred: ""
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
For assistance, contact your network support team.Your request was categorized by Blue Coat Web Filter as 'none'.If you wish to question or dispute this result, please click here.

-------------------------------------------------
Site entered is invalid (URL is on an internal network), please enter a valid site

--------------------------------------------------------------------------------------------------------------------
By entering a URL in the box below and clicking "Check Category", you are agreeing to the Symantec Website Terms of Use .

Site Review allows users to check and dispute the current WebPulse categorization for any URL. Note: This tool does not perform full real-time analysis of malicious URLs or files, which is included with the complete Symantec security solution.

Please enter a valid URL for the review process:
http&#x25;3A&#x25;2F&#x25;2F10.55.10.210&#x25;2Fview_customizes&#x25;2F3
-------------------------------------------------------------------------------------------------

**Comment by onozaty** [comment]
This message alone doesn't tell us what's wrong.
Is it an error that occurs when setting something with View customize?

**Comment by ashrafalzyoud** [comment]
what kind of settings???

**Comment by onozaty** [comment]
Is this problem related to View customize?
I didn't know what to look for from this information.

**Comment by ashrafalzyoud** [comment]
![1212](https://user-images.githubusercontent.com/50211455/90366108-a2783500-e06f-11ea-921d-76fd9a091282.png)
![12121212](https://user-images.githubusercontent.com/50211455/90366112-a3a96200-e06f-11ea-8dc4-ac009be4c8e2.png)
type css and html ok
type javascripts not ok
i want know the problem from plugin or from my settings firewall?

**Comment by onozaty** [comment]
Will all Redmine pages fail to open when an error occurs?

and, If I choose JavaScript, will all errors occur?
Even if you choose JavaScript, I would like to know if there is no problem pattern.

**Comment by ashrafalzyoud** [comment]
-->Type css,HTML work fine and I can create my view_customize and any code
--->Type JavaScript  No
If put code function() not work and give error
If I put any text without code like example "aaaaaaaa"in code for test 
It's ok
---------
It's strange I don't where the problem

**Comment by onozaty** [comment]
The issue below is working?
* https://github.com/onozaty/redmine-view-customize-scripts/issues/31 

Is the environment where it is running different?

**Comment by ashrafalzyoud** [comment]
If u can help me how I can find the error from plugin or MySQL or redmine or firewall ?

**Comment by onozaty** [comment]
If you look at the Redmine log and if there are no errors in the log, I think that it is a problem such as firewall.
