### ISSUE TITLE
Plugin registration in https://www.redmine.org/plugins directory

### ISSUE THREAD

**Issue by RealEnder** [onozaty/redmine-view-customize#68]
First, thank you for this useful plugin!
Please register plugin releases in https://www.redmine.org/plugins directory, so it will be easy to track and update the new versions via the administrative interface of Redmine.
Thanks!

**Comment by onozaty** [comment]
I have already registered in https://www.redmine.org/plugins directory, but the identifier was incorrect.

I just fixed it, so I think it's ok.
* https://www.redmine.org/plugins/view_customize

Thanks.

**Comment by RealEnder** [comment]
Great, now it works, thanks!
