### ISSUE TITLE
Not working at Redmine 4.1.1 (Bitnami) with undeinfed method before_filter error

### ISSUE THREAD

**Issue by yousan** [onozaty/redmine-view-customize#74]
Hello. I am really helped by this plugin ;)

I am trying to install a new Redmine with Bitnami latest version, but I got an error.
I got the error message at `apache/error_log`.

## Error

```
App 55766 output: Error: The application encountered the following error: undefined method `before_filter' for ViewCustomizesController:Class
App 55766 output: Did you mean?  before_action (NoMethodError)
App 55766 output:     /opt/redmine-4.1.1-6/apps/redmine/htdocs/plugins/view_customize/app/controllers/view_customizes_controller.rb:4:in `<class:ViewCustomizesController>'
```

```
/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
```

## Versions
I am using Bitnami.

https://bitnami.com/stack/redmine/README.txt
  - Redmine 4.1.1
  - Apache 2.4.46
  - ImageMagick 6.9.8
  - MySQL 5.7.32
  - Subversion 1.14.0
  - Git 2.29.2
  - Ruby 2.5.8
  - Rails 5.0.7.2
  - RubyGems 2.7.9

May I fix it?

Thank you.

**Comment by onozaty** [comment]
It looks like you have an older version of View customize installed.
How do you install it?

Thanks.

**Comment by onozaty** [comment]
Hi @yousan

Was it resolved?
If so, I would appreciate it if you could close it.

**Comment by yousan** [comment]
@onozaty Thank you for your response.
I could not resolve the issue... So I rollback the version of redmine and view-customize plugin.
So I close this issue.

I am happy continuing to use this plugin ;)

Thank you.

**Comment by onozaty** [comment]
@yousan 

The error is that there is no `before_filter`, but the current version of View customize does not use `before_filter`.
That's why I thought the version of View customize is outdated.

If you have version 2.0.0 or later of View customize, it supports Redmine4 + Rails5.

Thanks.
