### ISSUE TITLE
Thx, this is great!

### ISSUE THREAD

**Issue by runekaagaard** [onozaty/redmine-view-customize#75]
Hi @onozaty

Just wanted to say thank you for a great plugin. It just works and is the magic sauce that makes redmine perfect for us. We already have several small tidbits that removes the suck from certain pages.

So again. THX!

**Comment by onozaty** [comment]
Hi @runekaagaard 

I am very happy to receive your comment.
Thanks!

**Comment by onozaty** [comment]
If you like, I would be grateful if you could add a Star to this project 😄

**Comment by runekaagaard** [comment]
Maybe have a place to share users scripts? This little script for instance hides and makes toggleable all context in messages after given keywords, which is perfect for hiding duplicated content when the users replies to the issue via email:

```
function preToggleHidden(id) {
    $(`#${id}`).toggleClass("hidden")
}

(function () {

var phrases = [
    "Kind regards", 
    "Best",
    "On Mon, ", "On Tue, ", "On Wed, ", "On Thu, ", "On Fri, ", "On Sat, ", "On Son, ",
    // Insert you own phrases here to fold after.
]

$(".journal .wiki").each((i, el) => {
    const html = el.innerHTML
    var i = Number.MAX_VALUE
    for (let phrase of phrases) {
        let s = `<p>${phrase}`
        let i2 = html.toLowerCase().indexOf(s.toLowerCase())
        if (i2 === -1) continue
        i = Math.min(i, i2)
    }
    if (i !== Number.MAX_VALUE) {
        let id = `note-details-${i}`
        let a = html.slice(0, i)
        let b = html.slice(i, html.length-1)
        el.innerHTML = `
            ${a}
            <p onclick="preToggleHidden('${id}')" style="position: relative; margin-top: -14px"><a style="cursor: pointer; background-color: #EFF6FC; width: 30px; display: inline-block; text-align: center;" title="Show/Hide all">···</a></p>
            <div id="${id}" class="hidden">
                ${b}
            </div>
        `
    }
})
  
})();
```

**Comment by onozaty** [comment]
In the following project, we are exchanging information about the sample code.

* https://github.com/onozaty/redmine-view-customize-scripts

If you can post an issue there, others may be able to refer to it.

Thanks.
