### ISSUE TITLE
User and password

### ISSUE THREAD

**Issue by lcasanova78** [onozaty/redmine-view-customize#79]
I'm accessing the redmine API doing a $.get(.....) to get an xml of an issue, in the get command I add the user apikey (obtained with ViewCustomize.context.user.apiKey) and it asks for username and password. It asks for it the first time that I execute the command, if I introduce it, it doesn't ask for it again. Isn't it supposed that accessing with the apikey it is not necessary the user and password?

**Comment by onozaty** [comment]
If you have an API key, you don't need a password.
I think you must be doing something wrong.

Please refer to the following.

* https://github.com/onozaty/redmine-view-customize#api-access-key
* https://www.redmine.org/projects/redmine/wiki/rest_api#Authentication

**Comment by lcasanova78** [comment]
I have checked both 'Automatically create API access key' and 'Enable REST web service'
My code being the following:
  //Gets the user's apikey
    var apikey = ViewCustomize.context.user.apiKey;
    var parentkey = $('#issue_parent_issue_id').val();
    //Gets the xml of the parent issue
    $.get("https://gmvmine-pre.gmv.es/redmine-ad/issues/" + parentkey + ".xml?api_key=" + apikey, function (issue) {....

**Comment by onozaty** [comment]
I tried this with Redmine 4.1.
If you just want to GET, no API key was needed.

```javascript
$(function() {

  var parentkey = $('#issue_parent_issue_id').val();

  $.get(
    "http://192.168.33.41/issues/" + parentkey  + ".xml",
    function(data) {
      alert(data);
    });

})
```

**Comment by onozaty** [comment]
Also, the query parameter looks like a key, not api_key.

* https://www.redmine.org/projects/redmine/wiki/rest_api#Authentication

**Comment by lcasanova78** [comment]
Thank you very much for the help I have already solved it, the query can be closed
