### ISSUE TITLE
Can't appear view customize in admin menu

### ISSUE THREAD

**Issue by crosspointst** [onozaty/redmine-view-customize#8]
I manage some redmine site. One of these can't appear view customize in admin menu and I can't access view customize page directly. 
I've checked production.log, but no error. The installatin was success. 
This is my first experience. It appears in information page.
Please advice what I have to check.

Redmine version is 3.1.4, view customize is latest version.
On same environment, another same version redmine is working well.

Thanks.

**Comment by crosspointst** [comment]
Sorry, it's my mistake.
I forgot about redmine_admine_access plugin. It restrict accessing plugin and some administrator menu.

Please forget this issue.

**Comment by onozaty** [comment]
@crosspointst  Thank you for using.
All right. I closed.
