### ISSUE TITLE
Conditional custom fields not work after installing the view customize plugins.

### ISSUE THREAD

**Issue by yingsheng658** [onozaty/redmine-view-customize#9]
Hi Onozaty,

I have tried to implement it but not work,just follow the following link,
http://blog.enjoyxstudy.com/entry/2016/04/03/000000
When I select parent as "A",not only "A-1","A-2" can be selected but also "B-1" and "B-2".
Could you give me a favor.Thanks in advanced.
BTW,I do not know how to get the parentFieldId and the childFieldId from html source code also.

**Comment by onozaty** [comment]
Hi @yingsheng658 ,

The custom field may be incorrect.
Please check your project custom field id.

Please display the HTML source code and search with "issue_custom_field".

**Comment by yingsheng658** [comment]
Hi Onozaty,

I just view the HTML source code but cannot fine the keywords "issue_custom_field".Still need your help.
BTW,the screent shot of HJTML as below,
![image](https://user-images.githubusercontent.com/28344065/29502224-0625d4ac-8661-11e7-9f49-e75502c9c3e6.png)
What does "5" stand for?The parentFieldID?

**Comment by onozaty** [comment]
Hi @yingsheng658 ,

What is the name of the parent field?
Looking at the image, "cf_1" is 5 and "cf_1" is 6.

**Comment by yingsheng658** [comment]
Hi onozaty,

The name of parentFieldID is cf_1 and the name of childFieldID is cf_2.

**Comment by onozaty** [comment]
Please try the following.

```javascript
  var parentFieldId = 'issue_custom_field_values_5';
  var childFieldId = 'issue_custom_field_values_6';
```

**Comment by yingsheng658** [comment]
Hi onozaty,

Before submit this issue,I have tried to modify the script as you mentioned but still cannot work.

**Comment by onozaty** [comment]
Hi @yingsheng658 

Please look at the HTML of the ticket creation screen.
Is there an "issue_custom_field_values_5" and "issue_custom_field_values_6"?

**Comment by yingsheng658** [comment]
Hi onozaty,

Do you mean that the HTML as below screen shot?
![image](https://user-images.githubusercontent.com/28344065/29544912-d58a0486-871d-11e7-94a4-33948f44e1af.png)
If it does,I cannot find "issue_custom_field_values_5" and "issue_custom_field_values_6" from the HTML source code.

**Comment by yingsheng658** [comment]
Hi onozaty,

It's embarrassing that for my mistake,I just set parameter as "parentFieldID",and it's fine when I change the parameter to "parentFieldId".Thanks for your kindly support.

**Comment by yingsheng658** [comment]
Hi onozaty,

I got another question,if item B be selected from cf_1,and then only B-1 and B-2 can be selected,it's fine.
But before apply,I choose item A from cf_1 once again,how do I modify the script to clear the value of cf_2 if not clear the value of cf_1 before apply.Thanks in advanced.

**Comment by onozaty** [comment]
Hi @yingsheng658 

You can clear it by adding the following code.
```javascript
    var parentSelected = $('#' + parentFieldId + ' > option:selected');
    $('#' + childFieldId).val('');   // <-Add code 
```

Could you please give it a try.

**Comment by yingsheng658** [comment]
Hi onozaty,

It's fine,thanks for your kindly support.

**Comment by onozaty** [comment]
I am happy to help you.
