### ISSUE TITLE
Question regards View Customize and Custom Table Plugins

### ISSUE THREAD

**Issue by CristinaBascunana** [onozaty/redmine-view-customize#91]
Good afternoon,
I had a question regarding usage of both plugins together.
I was wondering if there is a chance to hide tables created with that plugin, for example, until the issue is closed, since I saw that there was an issue about data with tables that were created with Custom Table Plugin.

Thanks beforehand.

Kind regards

**Comment by onozaty** [comment]
Hi @CristinaBascunana 

If there is information available to determine which tables are problematic, I believe they can be hidden in View customize.
However, since I don't know what the problem is, it is difficult to give advice.

Thanks.

**Comment by CristinaBascunana** [comment]
Hi!
After some struggling with it and a lot of testing I was able to hide them.

Thank you so much for answering.
Have a nice evening!
